### PR TITLE
Make left nav slot sensitive to activePage

### PR DESCRIPTION
**Pull request by brandones**
Depends on https://github.com/openmrs/openmrs-esm-core/pull/45

Screenshots taken after doing

```
attach("nav-menu-home", "active-visits-link");
attach("nav-menu-patient-chart", "reports-link");
```

home-ext
pt-chart-ext

### CODE REVIEW

**Comment by FlorianRappl** [comment]
I am not sure what this is about. The different registrations need to be aware of the page. You are now using an extension slot per page. How can one module / extension know what pages exist? Imho this is neither necessary nor beneficial.

**Comment by brandones** [comment]
Here is the problem: _the left nav sidebar needs to contain different links based on what page the user is on_. This solves that problem by creating an extension slot which is specific to each page. If you want to reject this solution, please describe an alternative.

Extensions, by design, make guesses about what exists in the rest of the app. If module "esm-hiv-app" attaches an "hiv-link" extension to "left-nav-home" and "left-nav-patient-chart" but neither of those exist (because the modules that define those slots aren't being used), that's totally fine. The implementer can use the config to attach "hiv-link" somewhere else.

**Comment by FlorianRappl** [comment]
> Here is the problem: the left nav sidebar needs to contain different links based on what page the user is on. This solves that problem by creating an extension slot which is specific to each page.

If a link should be visible on a page should be left to the link, don't you think? If a link is fine with the URL it will proceed, otherwise it would just refuse to show.

Generally, my idea was rather to attach extensions (i.e., links) to this slot on an activate (mount) and detach them on unmount. No need for a new concept.

**Comment by FlorianRappl** [comment]
> Extensions, by design, make guesses about what exists in the rest of the app.

Hm not in my design. In my design an extension only cares about its state. It cares about what parameters it receives. That's it. No other assumption necessary for the extension itself.

Surely, the creator of an extension envisions the extension to be used in a specific context. But that's natural. We are humans after all - having too many layers of abstractions don't help us thinking about something specifically. Planning requires knowing the inventory.

**Comment by brandones** [comment]
Right, well that's profoundly different than https://github.com/openmrs/openmrs-rfc-frontend/pull/27 . But sure, let's discuss that approach. Maybe that is the right design.

Correct me if I'm wrong, but it sounds like you're suggesting that link extensions be structured like this:

```jsx
function HivLink({ route }) {
  if (route.matches(/^patient\/.+\/chart/)) {
    return <a href="hiv">HIV</a>
  }
}

export function setupOpenMRS() {
  return {
    extensions: [
      id: "hiv-link",
      load: () => getExtensionLifecycle(HivLink),
      slot: "left-nav"
    ]
  }
}
```

**Comment by FlorianRappl** [comment]
Its one potential design, but I'd rather not design it like that. I'd design it more like:

```jsx
function HivLink() {
  return <a href="hiv">HIV</a>
}

export function setupOpenMRS() {
  return {
    pages: [
       {
        load: () => {
          mount() {
            attach("hiv-link", "nav-left");
          },
          unmount() {
             detach("hiv-link", "nav-left");
          },
        },
        activate: /^patient\/.+\/chart/,
      }
    ],
    extensions: [
      id: "hiv-link",
      load: () => getExtensionLifecycle(HivLink)
    ]
  }
}
```

This way the extension itself is well separated from the use later allowing reuse.

**Comment by brandones** [comment]
Nice! That's very clear, thank you for the example code.

In your model, if an implementer (i.e., not a programmer) says "I want the HIV Link to also appear in the left nav on the home page," how do they accomplish that?

**Comment by FlorianRappl** [comment]
> In your model, if an implementer (i.e., not a programmer) says "I want the HIV Link to also appear in the left nav on the home page," how do they accomplish that?

First of all we would need to clarify if that is really a wanted flexibility. Personally, I have yet to see somebody using / doing that. And yet we spent 95% of the time fulfilling requirements that will rarely (if ever) be used. If somebody wants to change *everything* then just dropping a microfrontend and replacing it should be the way.

Nevertheless, let's suppose we want to have that flexibility, why not just add a configuration in that microfrontend? That's why we have it, right? So you just configure, e.g., the URL it should be sensitive to. Or you configure the type of panel (menu) you want it to attach to. We just grab that configuration and use it here.

**Comment by FlorianRappl** [comment]
I don't think that the scaling approach of microfrontends is really well understood right now.

You cannot explicitly answer everything in one microfrontend or position. This is impossible. Likewise, we cannot say "yeah we just explicitly state where the link should be used". This is impossible.

1. Not all microfrontends are in our hands.
2. Even if they are, we will not keep up to date with what pages are there.
3. Even if that is accomplished we can never make that really transparent to the user.
4. Even if the user knows all the pages and has the guts to say "this link here, that link there, ..." he will be confused why he cannot just use the existing configuration / extension system to do that. Why yet another special variant?

Don't get me wrong - I know the intention here and I agree; having a way to be URL sensitive is great. I just feel we should not bring in too many extra things. They make the solution unnecessary complex and fragile. We already have too many extra stuff in there. I'd always first look into "what do we have or what could we extend / improve to make this work?".

**Comment by brandones** [comment]
> First of all we would need to clarify if that is really a wanted flexibility.

As someone who has implemented OpenMRS for a medical facility, yes, it is.

> Nevertheless, let's suppose we want to have that flexibility, why not just add a configuration in that microfrontend? That's why we have it, right? So you just configure, e.g., the URL it should be sensitive to. Or you configure the type of panel (menu) you want it to attach to.

Could you provide some pseudocode, for either of those ideas? The latter could be interesting.

**Comment by brandones** [comment]
> I don't think that the scaling approach of microfrontends is really well understood right now.

I think that we have two different paradigms, which are colliding. My paradigm is explained in the [implementation plan](https://github.com/openmrs/openmrs-rfc-frontend/pull/27) and the linked slide decks. It's essential points are that
1. Extensions do not need to know any contextual information, including the route at which they are mounted.
2. Extensions can be attached to extension slots anywhere in the app, at any route. The only requirement is that the necessary context be present—if an extension uses the current patient, it can only be used in a page that has a current patient.
3. Attachments between slots and extensions can be created programmatically.
4. If the extension or slot doesn't exist, the attachment is ignored.
5. Extensions can be attached, detached, or reordered with respect to any slot using configuration.

Your paradigm clearly diverges with respect to (1). It may diverge with respect to (2), (4), and (5) as well. It seems to involve extension slots that have route patterns for names, which makes the model vastly more complicated, and I have no idea what the use case for this is. It also seems to presume that generally an extension will only be attached to a single "slot" (per the extension registration). You also seem to have different ideas about what an "extension ID" is supposed to be.

I think that the collision between your model and mine is producing a lot of probably unnecessary complexity. Things that are natural in my paradigm look like "special variants" to you, and things that are natural in your paradigm look like "special variants" to me.

I cannot tell, and neither can anyone else, whether the solution you propose is actually simpler and more flexible. This is because you have never really described your model of an extension system in a holistic way. You provided the basic ideas of an extension system, and for that, thank you. But clearly there are paradigmatic differences between our models, and I'd like it if you actually proposed your model, rather than making changes to the actually existing model that don't really make any sense within it, and indeed make it more complicated than it is intended to be.

**Comment by FlorianRappl** [comment]
> I cannot tell, and neither can anyone else, whether the solution you propose is actually simpler and more flexible. This is because you have never really described your model of an extension system in a holistic way. You provided the basic ideas of an extension system, and for that, thank you. But clearly there are paradigmatic differences between our models, and I'd like it if you actually proposed your model, rather than making changes to the actually existing model that don't really make any sense within it, and indeed make it more complicated than it is intended to be.

No need for personal attacks here. Just try to follow me - I'll try to be more precise.

Instead of thinking in terms of URLs and coming up with different ways of achieving the same we should always try to come up with a consistent state for the end user. As such let's do that in form of an example. Let's suppose we want to implement nav items that are only shown *in the context of* patient chart. Well, let's let patient chart handle that, shall we?

```diff
import { getAsyncLifecycle } from "@openmrs/esm-react-utils";
import { defineConfigSchema } from "@openmrs/esm-config";
import { esmPatientChartSchema } from "./config-schemas/openmrs-esm-patient-chart-schema";
import { backendDependencies } from "./openmrs-backend-dependencies";

const importTranslation = require.context(
  "../translations",
  false,
  /.json$/,
  "lazy"
);

function setupOpenMRS() {
  const moduleName = "@openmrs/esm-patient-chart-app";

  const options = {
    featureName: "patient-chart",
    moduleName
  };

  defineConfigSchema(moduleName, esmPatientChartSchema);

  return {
    lifecycle: getAsyncLifecycle(() => import("./root.component"), options),
    activate: /^patient\/.+\/chart/,
+    extensions: [
+      { id: "patient-chart-nav-items", load: getAsyncLifecycle(() => import("./nav-items.component"), options) }
+    ]
  };
}

export { backendDependencies, importTranslation, setupOpenMRS };
```

where we introduce a simple carrier `nav-items.component.tsx` which could be close to:

```jsx
export default function NavItems() {
  return <ExtensionSlot extensionSlotName="patient-chart-nav-menu" />;
}
```

and `root.component.tsx` would be extended to have a hook like

```tsx
useEffect(() => {
  attach("patient-chart-nav-items", "nav-menu");
  return () => detach("patient-chart-nav-items", "nav-menu");
}, []);
```

Now a link that only wants to appear *in the context* of patient-chart, will just add there:

```ts
attach("my-own-nav-link", "patient-chart-nav-items")
```

such as

```jsx
function setupOpenMRS() {
   return {
    extensions: [
      {
        id: 'my-own-nav-nav-link',
        slot: 'patient-chart-nav-menu',
        load: getAsyncLifecycle(() => import('./nav-link.component'), options),
      },
    ],
  };
}
```

There is no need to know about any URLs. If the patient chart URL changes this one still works as its just bound to the one context. If the given extension ID should be attached to some other context specific menu list you can do that, too.

Hope that makes it a bit more clear. Happy to implement that out if desired.

**Comment by brandones** [comment]
Thanks for the example code. That really makes it clear exactly what you're proposing (it is very different from what I thought you were proposing). I think that's a very reasonable solution. Please feel free to implement it.

I still think our collaboration would benefit from a holistic description of the extension system you envision, given its aforementioned paradigmatic differences from the one I've proposed and mostly implemented. But that can be another day. No personal attacks intended.

**Comment by FlorianRappl** [comment]
I think you are totally right and that we (or I - for this matter) should actively contribute to the RFC.

What would help me is to have a dual strategy on the RFC. Maybe you agree to this:

1. Take the RFC forward (update to what we implemented; have in mind to implement)
2. Use specific examples / patterns and include them in the docs in esm-core. Referring to the RFC if helpful / for completeness

What is your thought on this?

**Comment by brandones** [comment]
Sounds great. Thanks Florian.

**Pull request closed without merging**
